name: docker-build-and-push

on:
  workflow_dispatch:
    inputs:
      # for example: version-2.17
      linkerd-version:
        description: 'A linkerd release or tag'
        required: true
      # for example: v2.276.0
      proxy-version:
        description: 'A linkerd proxy release or tag'
        required: true



jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
      packages: read

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: ${{ inputs.linkerd-version }}

      - name: Build Docker images
        id: build-image
        run: |
          cd bin

          echo "${{ inputs.proxy-version }}" > .proxy-version
          
          ./docker-build-proxy
          ./docker-build-controller
          ./docker-build-jaeger-webhook

          docker images













